name: test

on: [push, pull_request]

jobs:
  test:
    name: Nacos-${{ matrix.nacos }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        nacos: ['v2.1.0', 'v2.0.4', 'v1.4.3', '1.3.2', '1.2.1', '1.1.4', '1.0.1']
    env:
      NACOS_VERSION: ${{ matrix.nacos }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: |
          docker-compose -f .github/docker-compose.yml up -d
      - name: Wait for container
        uses: stringbean/docker-healthcheck-action@v1
        with:
          container: nacos
          wait-time: 120
          require-status: running
          require-healthy: true
      - name: Test PHP 8.1
        if: ${{ always() }}
        run: |
          docker exec php8.1 composer update
          docker exec php8.1 composer test
      - name: Test PHP 8.0
        if: ${{ always() }}
        run: |
          docker exec php8.0 composer update
          docker exec php8.0 composer test
      - name: Test PHP 7.4
        if: ${{ always() }}
        run: |
          docker exec php7.4 composer update
          docker exec php7.4 composer test
